# PostgreSQL Properties - Implement externalized configuration for DB Password and usernames using environment variables
spring.datasource.url=jdbc:postgresql://localhost:5432/timesheet_service_management
spring.datasource.username=enter_your_DB_name
spring.datasource.password=enter_your_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver


#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Set the JWT token timeout
springdoc.packagesToScan=com.timesheetmanagement.controller
springdoc.pathsToMatch=/api/**
jwt.token.expiration-in-ms=set_jwt_token_timeouts

com.timesheetmanagement.image.profile.folder.path=/Users/<<Used_ID>>/workspace-spring-tool-suite-4-4.27.0/Timesheet Management System/image

# email smtp setup
# enter your email id
# login with this email id in your Google Account
# generate the App Password and enter that password here
# Note: don't enter your actual email password here
#Add these configurations to .env file
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=enter_your_email
spring.mail.password=enter_your_email_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
