# PostgreSQL Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/timesheet_service_management
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver


#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.packagesToScan=com.timesheetmanagement.controller
springdoc.pathsToMatch=/api/**
jwt.token.expiration-in-ms=86400000

com.timesheetmanagement.image.profile.folder.path=/Users/jagadeeswarreddy/Documents/workspace-spring-tool-suite-4-4.27.0.RELEASE/Timesheet Management System/image

# email smtp setup
# enter your email id
# login with this email id in your Google Account
# generate the App Password and enter that password here
# Note: don't enter your actual email password here
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=timesheetmanagement15@gmail.com
spring.mail.password=qdsmfikucwoetasy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true